### ISSUE TITLE
can't connect to jellyfin after installation on truenascore to 192.168.1.94:8096

### ISSUE THREAD

**Issue by davide11** [Thefrank/jellyfin-server-freebsd#79] opened 2024-06-16 07:58 UTC
Hello,

I'm trying since 3 hours how can I connect to jellyfin after the installation in true nas core.
I have already installed jellyfin and when I go to 192.168.1.94:8096 the page doesn't work and get me: connection don't work

see pictures attached.

Could you help to me? I don't have idea...

Maybe I know that with other port it could work, but I don't know how can I change the port in jellyfin truenas core 

![2](https://github.com/Thefrank/jellyfin-server-freebsd/assets/25763106/7f8b339c-b412-457c-8637-18ddd1640c02)
![Cattura](https://github.com/Thefrank/jellyfin-server-freebsd/assets/25763106/6a4aa8f8-0db0-41a1-ab49-3dae63f2778e)

**Comment by ageekhere** [comment] 2024-06-16 12:12
Jellyfin 10.9.4 needs the TrueNAS CORE 13.3 update, which is not out yet but should be very soon
see https://github.com/Thefrank/jellyfin-server-freebsd/issues/75

**Comment by Thefrank** [comment] 2024-06-16 13:28
Duplicate of #75. There are some workarounds but I suggest waiting for iXSystems to update TrueNAS Core.

**Closed by Thefrank** 2024-06-16 13:28 UTC
