### ISSUE TITLE
Jellyfin not running a webserver

### ISSUE THREAD

**Issue by ZigEEEEE** [Thefrank/jellyfin-server-freebsd#76] opened 2024-06-06 15:21 UTC
I have jellyfin 10.9.4 installed on a 13.2 jail in TrueNAS. The service IS running in the jail:
![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/80275901/f3bae3fa-09c9-42e7-9fa6-c61e31c0d9d8)
However, no web interface is hosted and no ports have been opened:
![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/80275901/29d5d78c-e371-4fca-b60f-db3b00e2bb41)
As you can see, no TCP or UDP ports have been opened.
I have ensured mlock is enabled, IPv6 is set to inherit and all available versions of jail have been tried (13.2, 13.3, 12.4).
My TrueNAS version is 13.0-U6.1
I have changed my pkg version to latest and not quarterly to get jellyfin 10.9.4 to install at all.

I really have no idea why I can't go to port 8096 on my PC (NAT forwarding is turned on for ports 8096, 8920, 1900, 7359).
Help would be greatly appreciated.

**Comment by Thefrank** [comment] 2024-06-06 15:43
Are there two `jellyfin` processes listed in the process list (`ps`)? One will be the daemon and the other will be the jellyfin process.
Does `sockstat` show ports that `jellyfin` uses?

Finally: Running a jail that is newer than the host can result in unexpected/unknown behavior. You can look at https://github.com/Thefrank/jellyfin-server-freebsd/issues/75 to get a better idea of the problems that might occur between TrueNAS 13.0 (based on FreeBSD 13.1) and FreeBSD 13.2/13.3

**Comment by ZigEEEEE** [comment] 2024-06-06 16:07
![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/80275901/9e53af8e-107d-4ab3-8476-dd0e1e771300)
Still, no ports are open

**Comment by ZigEEEEE** [comment] 2024-06-06 16:08
![image](https://github.com/Thefrank/jellyfin-server-freebsd/assets/80275901/f5f4a30e-6bcf-4281-9088-6e713a733ba0)
It seems jellyfin is not running after all?

**Comment by ZigEEEEE** [comment] 2024-06-06 16:11
If it is a TrueNAS version issue, how do you think I should proceed? Should I change to TrueNAS 13.3 beta?

**Comment by Thefrank** [comment] 2024-06-06 16:13
oops! `ps auxw | grep jellyfin` might be the easiest way to dig it out of a list. If the PID is changing often it means that the service is trying to restart a crashing program

This does seem to be a duplicate of #75. A few people have figured out workarounds, otherwise you can wait for a version of TrueNAS based on FreeBSD 13.3 or higher.

**Comment by ZigEEEEE** [comment] 2024-06-06 16:16
I might switch to the beta which is based on 13.3, thanks!

**Closed** 2024-06-06 16:16 UTC
