### ISSUE TITLE
FreeBSD 14 - OpenSSL3 issue

### ISSUE THREAD

**Issue by spin24** [Thefrank/jellyfin-server-freebsd#62] opened 2023-11-10 18:31 UTC
Since OpenSSL 3 importing into the base system in FreeBSD 14, jellyfin server can't start now. 

When upgrading to 14.0-R, I add default options for SSL in make.conf
`
DEFAULT_VERSIONS+=ssl=base
`
And rebuild related ports. 
But jellyfin service can't start. 

Have to install [security/openssl111/](https://www.freshports.org/security/openssl111/) to make it work again. 

Any advice? 
Thanks.

**Comment by Thefrank** [comment] 2023-11-11 03:40
dotNET is built under FreeBSD 12.4 and 13.2. JF should work on 12.4 and 13.2 but will not work under 14 because of the new OpenSSL version. When 14.0-R releases I will take a look at what changes need to be made to build dotNET but until you need to use OpenSSL 1.1.1

This also means I have to unlazy myself and actually build ABI specific binaries for everything I do


This is a reminder to others reading this: Binary usability between FreeBSD versions, both major and minor is considered a bug not a feature.

**Comment by louwe** [comment] 2023-12-10 17:02
For those running into this problem. I just run it in a jail that is running 13.2-RELEASE and it should tide you over until the port is upgraded to support 14.0-RELEASE.

Depending on how you manage your jails, this can be super trivial. I am using BastilleBSD and it's a simple modification of 14.0 back to 13.2 on the jail's fstab file.

**Comment by spin24** [comment] 2024-01-01 16:17
After the port version 10.8.13 https://www.freshports.org/multimedia/jellyfin/ , the issue was solved. 
FYI: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=275249

**Comment by Thefrank** [comment] 2024-01-01 19:23
This should be resolved in ports via workaround but I am keeping this open until I can get around to making ABI specific jellyfin builds

**Comment by louwe** [comment] 2024-01-03 03:09
Thanks for the update. Does this mean that I can now upgrade my jail to 14.0-RELEASE and it should start?

**Comment by Thefrank** [comment] 2024-01-03 04:54
FreeBSD:14:amd64 "Latest" should have it. "Quarterly" does not.

**Comment by louwe** [comment] 2024-01-03 13:01
That's perfect. All my jails already uses latest. Thank you.

**Comment by louwe** [comment] 2024-04-23 21:47
FYI, looks like version 10.8.13_1 reverted back to openssl111. Any ideas why?

**Comment by louwe** [comment] 2024-04-23 22:01
@Thefrank Thanks. Any plans on fixing the pkg version? I'd also like to know why the regression happened because 10.8.13 did work.

**Comment by Thefrank** [comment] 2024-04-23 22:17
@louwe 

Short: The port should be working. Better support from the binary will be in the next jellyfin build.

Long:
Direct detection and use of OpenSSL3 (3.0) on FreeBSD will be in dotNET9. I backported the support to dotNET8. The experimental build is from upstream master, uses dotNET8, and includes some other patches (e.g., VAAPI and QSV support).

The port version should be able to work around the previously missing support by setting `CLR_OPENSSL_VERSION_OVERRIDE=30`
https://github.com/freebsd/freebsd-ports/blob/215f85934c8bd6674008dcd402091a36a54074aa/multimedia/jellyfin/files/jellyfin.in#L70

**Comment by louwe** [comment] 2024-04-23 22:24
Thanks for the long and short explanations!

**Comment by louwe** [comment] 2024-07-21 22:37
Verified. I am now running it on 14.1-RELEASE without any modifications.
Thanks for the help!

**Closed** 2024-07-22 03:20 UTC
Labels: bug, enhancement
